name: avaliacao_tecnologia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # O seu SDK pode ser um pouco diferente

# -----------------------------------------------------------------
# SUAS DEPENDÊNCIAS DE APLICATIVO
# -----------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  # Dependência do Supabase
  supabase_flutter: ^2.5.8 
  
  # Pacote para chamadas de API (Pokémon)
  http: ^1.2.1
  
  cupertino_icons: ^1.0.6

# -----------------------------------------------------------------
# SUAS DEPENDÊNCIAS DE DESENVOLVIMENTO
# -----------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  
  # Pacote do Ícone (Note a indentação de 2 espaços)
  flutter_launcher_icons: ^0.13.1

# -----------------------------------------------------------------
# CONFIGURAÇÃO DO FLUTTER
# -----------------------------------------------------------------
flutter:
  uses-material-design: true

  # Se você criou a pasta "assets" para o ícone,
  # é bom declará-la aqui também (opcional, mas boa prática)
  # assets:
  #   - assets/icon/

# -----------------------------------------------------------------
# CONFIGURAÇÃO DO LAUNCHER ICONS (Nível Raiz, sem indentação)
# -----------------------------------------------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Verifique se seu caminho é este